### ISSUE TITLE
\d <table> doesn't work

### ISSUE THREAD

**Issue by diogohal** [MonetDB/MonetDB#7340] opened 2022-11-11 13:45 UTC
**Describe the bug**
I'm trying to get the table schemas of my database with \d <table_name>, but the following error message appear in all of them (I'm using "matricula" as example):
```
CREATE TABLE "sys"."matricula" (
MAPI  = (monetdb) /tmp/.s.monetdb.50000
QUERY = SELECT c.name, c.type, c.type_digits, c.type_scale, c."null", c."default", c.number FROM sys._columns c, sys._tables t, sys.schemas s WHERE c.table_id = t.id AND t.name = 'matricula' AND t.schema_id = s.id AND s.name = 'sys' ORDER BY c.number
ERROR = !GDK reported error: project_sht: does not match always
malloc failure
```
Apparently the issue is in sys.__columns table, because when I try to select the data from it the same error appears.
```
sql>select * from sys._columns
more>;
GDK reported error: project_sht: does not match always
```

**To Reproduce**
1) Create example table

```
create table fonte(
id integer not null,
tabela char(38) not null,
fonte char(128) not null
);
```

2) Show the table schema with \d

`\d fonte`

**Expected behavior**
The table schema should appear

**Actual behavior**
The error message appears

**Software versions**
 - MonetDB version: MonetDB Database Server Toolkit v11.41.11 (Jul2021-SP1)
 - OS and version: Debian GNU/Linux 10
 - Installed from release package

**Issue labeling**
Schema error

**Comment by lrpereira** [comment] 2022-11-11 14:17
Hi Diogo,
Thanks for reporting.
Quick question: is there a particular reason why you are using Jul2021-SP1 ?

Update:
I'm not able to reproduce this issue on a fresh DB.

**Comment by diogohal** [comment] 2022-11-11 14:41
No particular reason.

**Comment by lrpereira** [comment] 2022-11-11 14:43
The project error is one of the symptoms of a corrupted DB.
Can you try dumping the DB and restore it on the newest release (Sep2022) ?

**Comment by diogohal** [comment] 2022-11-11 14:53
The dump generates a similar error
```
root@simcaqdb3:~# msqldump --database=simcaq-dev > ~/DataTeam/dump.sql
MAPI  = (monetdb) /tmp/.s.monetdb.50000
QUERY = SELECT c.name, c.type, c.type_digits, c.type_scale, c."null", c."default", c.number FROM sys._columns c, sys._tables t, sys.schemas s WHERE c.table_id = t.id AND t.name = 'regiao' AND t.schema_id = s.id AND s.name = 'sys' ORDER BY c.number
ERROR = !GDK reported error: project_int: does not match always
malloc failure
MAPI  = (monetdb) /tmp/.s.monetdb.50000
QUERY = SELECT subq.s1name, subq.t1name, subq.s2name, subq.t2name, table_partitions.type FROM (SELECT t1.id, t1.type, s1.name AS s1name, t1.name AS t1name, s2.name AS s2name, t2.name AS t2name FROM sys.schemas s1, sys._tables t1, sys.dependencies d, sys.schemas s2, sys._tables t2 WHERE t1.type IN (3, 6) AND t1.schema_id = s1.id AND s1.name <> 'tmp' AND t1.system = FALSE AND t1.id = d.depend_id AND d.id = t2.id AND t2.schema_id = s2.id ORDER BY t1.id, t2.id) subq LEFT OUTER JOIN sys.table_partitions ON subq.id = table_partitions.table_id
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005
```
The dump file result is
```
  1 -- msqldump version 11.41.11 (Jul2021-SP1) dump database
  2 -- server: MonetDB v11.41.11 (Jul2021-SP1), 'mapi:monetdb://simcaqdb3:50000/simcaq-dev'
  3 -- Fri Nov 11 11:49:53 2022
  4 START TRANSACTION;
  5 CREATE SEQUENCE "sys"."seq_123620" AS INTEGER;
  6 CREATE SEQUENCE "sys"."seq_123665" AS INTEGER;
  7 CREATE SEQUENCE "sys"."seq_123690" AS INTEGER;
  8 CREATE SEQUENCE "sys"."seq_123712" AS INTEGER;
  9 CREATE SEQUENCE "sys"."seq_123734" AS INTEGER;
 10 CREATE SEQUENCE "sys"."seq_123962" AS INTEGER;
 11 CREATE SEQUENCE "sys"."seq_142357" AS INTEGER;
 12 CREATE SEQUENCE "sys"."seq_190480" AS INTEGER;
 13 CREATE SEQUENCE "sys"."seq_391529" AS INTEGER;
 14 CREATE SEQUENCE "sys"."seq_7501" AS INTEGER;
 15 CREATE SEQUENCE "sys"."seq_7510" AS INTEGER;
 16 CREATE SEQUENCE "sys"."seq_8555" AS INTEGER;
 17 CREATE SEQUENCE "sys"."seq_89804" AS INTEGER;
 18 CREATE SEQUENCE "sys"."seq_94087" AS INTEGER;
 19 CREATE SEQUENCE "sys"."seq_94719" AS INTEGER;
 20 CREATE SEQUENCE "sys"."seq_95816" AS INTEGER;
 21 CREATE SEQUENCE "sys"."seq_95887" AS INTEGER;
 22 CREATE SEQUENCE "sys"."seq_96170" AS INTEGER;
 23 CREATE SEQUENCE "sys"."seq_96345" AS INTEGER;
 24 CREATE SEQUENCE "sys"."seq_96391" AS INTEGER;
 25 CREATE SEQUENCE "sys"."seq_96561" AS INTEGER;
 26 CREATE SEQUENCE "sys"."seq_98976" AS INTEGER;
 27 CREATE SEQUENCE "sys"."seq_98997" AS INTEGER;
 28 CREATE SEQUENCE "sys"."seq_99095" AS INTEGER;
 29 SET SCHEMA "sys";
 30 CREATE TABLE "sys"."regiao" (
```
The process is interrupted probably after accessing sys._columns

**Comment by lrpereira** [comment] 2022-11-14 12:45
System tables are corrupted.
Most likely it is the same particular bug that we have been experiencing in the past and that is fixed on the latest version.
Update MonetDB to the latest version and restore your data from a possible backup.
Let me know if you have any questions.

**Comment by diogohal** [comment] 2022-11-16 12:22
I will do that. Thank you for the help.

**Comment by lrpereira** [comment] 2022-11-16 12:26
You're welcome.
Closing the issue for now.
Re open if any issue related to this one arises.

**Closed as completed by lrpereira** 2022-11-16 12:26 UTC
