### ISSUE TITLE
Hibernate ID generation usage with monetdb

### ISSUE THREAD

**Issue by Cobas91** [MonetDB/MonetDB#7421] opened 2023-11-28 08:53 UTC
**Describe the bug**
We used Version 11.45.11 in combination with Spring Hibernate 5.6.10. Because there was no Hibernate Dialect for Monet we used the MYSQL Hibernate dialect. Everything works fine in that version of Monet.
After a version upgrade to 11.47.11 SP3 we got this error.
`could not prepare statement; SQL [select last_insert_id()]`

I guess its not really a bug just more a feature request.
Is there an implementation for a hibernate dialect for monet?

**To Reproduce**
Create a Hibernate Entity with a Integer ID and GenerationType Identity. And save it with a JPA Repository to MonetDB.
Use MYSQL as Hibernate Dialect

**Expected behavior**
Use the DB Engine to handle the ID generation without a sequence.

**Software versions**
Hibernate - 5.6.10
Monet 11.47.11 SP3

**Additional context**

**Comment by njnes** [comment] 2023-12-02 15:17
MonetDB doesn't have the last_insert_id function. But it already includes the last_id in the data sent to the client, when the insert statement was done. So obtaining the values should be doable. But it seems currently the jdbc driver doesn't keep this value and has no api to return it.

**Comment by joerivanruth** [comment] 2023-12-03 14:14
JDBC has an API [Statement.getGeneratedKeys()](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#getGeneratedKeys) to obtain the id.

Note that this only works if the id is generated from a SEQUENCE, for example if the id column has type `SERIAL`. 

Here is an example.

```
private static void testGeneratedKeys(Connection conn) throws SQLException {
    int key;
    try (Statement stmt = conn.createStatement()) {
        stmt.execute("DROP TABLE IF EXISTS foo;");
        stmt.execute("CREATE TABLE foo(id SERIAL, t TEXT);");

        // dummy data
        stmt.execute("INSERT INTO foo(t) VALUES ('a'), ('b');");

        // insert and get key used
        stmt.execute("INSERT INTO foo(t) VALUES ('c')");
        try (ResultSet keys = stmt.getGeneratedKeys()) {
            if (!keys.next()) {
                throw new RuntimeException("no generated key found");
            }
            key = keys.getInt(1);
        }
    }

    System.out.println(key);

    // verify key value
    try (PreparedStatement stmt = conn.prepareStatement("SELECT t FROM foo WHERE id = ?")) {
        stmt.setInt(1, key);
        try (ResultSet rs = stmt.executeQuery()) {
            if (!rs.next()) {
                throw new RuntimeException("no row with key " + key);
            }
            String value = rs.getString(1);
            if (!value.equals("c")) {
                throw new RuntimeException("Value at row id=" + key + " is not 'c' but '" + value + "'");
            }
        }
    }
}


```

**Comment by mvdvm** [comment] 2023-12-06 21:13
For clarity, do you use the latest MonetDB JDBC driver  [monetdb-jdbc-3.3.jre8.jar](https://www.monetdb.org/downloads/Java/monetdb-jdbc-3.3.jre8.jar) ?

**Comment by mvdvm** [comment] 2024-01-04 20:15
Our  JDBC driver supports the getGeneratedKeys() method for identity columns, so it should work. We have a test for this.

In order to analyse your reported error, we need a small standalone (1 source file) Java program which uses JDBC API only (so without any dependency on Hibernate or Spring) and produces the error when run against MonetDB server.
Can you provide it?

**Comment by mvdvm** [comment] 2024-01-18 19:46
Can you please respond to the requested information?
Else we have to close this.

**Comment by mvdvm** [comment] 2024-02-08 12:23
We can't reproduce your issue, so closing this issue.

Our JDBC driver supports returning the generated ID value, via the Statement.getGeneratedKeys() method. This works for identity columns, such as the serial datatype.
We don't know how hibernate creates such a table. You used the MySQL hibernate dialect, which probably does not generate the correct SQL CREATE TABLE statement for MonetDB.

We do not have a MonetDB dialect for hibernate. That is something that should be added to hibernate.

**Closed as completed by mvdvm** 2024-02-08 12:23 UTC
Labels: other

**Comment by mvdvm** [comment] 2024-02-08 17:28
See also MonetDB dialect request: [https://hibernate.atlassian.net/browse/HHH-14488](https://hibernate.atlassian.net/browse/HHH-14488)
