### ISSUE TITLE
SQL is not returning the column name properly - Monet SP3 Oct 2020 11.39.13 version Bug

### ISSUE THREAD

**Issue by bharaththam** [MonetDB/MonetDB#7095] opened 2021-04-02 13:45 UTC
Monet SP3 Oct 2020 11.39.13 version Bug
Issue:
With latest MonetDB version and ODBC version SP3 in this case (11.39.13) throws error for SELECT SUM  sql in ODBC layer.
 
Description:
SQL is not returning the column name properly. Error is as below
 
SQLDescribeCol: typeODBC: Unknown ODBC type! (16384) mDataType: HG_NULL_VALUE(hgColumnType) precision: 39 scale: 0 nullable: true Column name: %5. Setting this column to hgBinary_column type.
 
 
Executing the below SQL query in monetdb and ODBC version (11.39.13):
SELECT SUM("TM_DIM_ABC_39880".YR_AGO_KEY) FROM "TM_DIM_ABC_39880" WHERE (("TM_DIM_ABC_39880".HIER_FLG IN (25)) AND ("TM_DIM_ABC_39880".ROLLING IN (31078)) AND ("TM_DIM_ABC_39880".TM_UNIFORM_KEY = 150181958));
 
+----------+
| %5       |
+==========+
| 88006940 |
+----------+
 
Executing the below SQL query in monetdb and ODBC version (11.29.13):
SELECT SUM("TM_DIM_ABC_39880".YR_AGO_KEY) FROM "TM_DIM_ABC_39880" WHERE (("TM_DIM_ABC_39880".HIER_FLG IN (25)) AND ("TM_DIM_ABC_39880".ROLLING IN (31078)) AND ("TM_DIM_ABC_39880".TM_UNIFORM_KEY = 150181958));
 
+----------+
| L3       |
+==========+
| 88006940 |
+----------+

**Comment by yzchang** [comment] 2021-04-02 16:08
`%5` is not the problem here.  It is MonetDB's new format for automatically generated column names (I don't know by heart since which version it was).  It's a valid SQL identifier but is less likely to conflict with a user-defined column name than the old format (i.e. `L3`).

The real problem is `Unknown ODBC type! (16384)`, which is about MonetDB's `HUGEINT` type.  Your application doesn't recognise this data type, hence the error message.

In versions before Oct2020, `HUGEINT` support was optional.  MonetDB will only use it if the separate package is installed.  From the Oct2020 release, we no longer have a separate package for the 128-bit integer support (i.e. `HUGEINT`). It is now always enabled.

The problem is now caused by a discrepancy between the MonetDB ODBC driver and the application. The driver passes on information about so-called HUGEINT columns to the application, using an ODBC extension type that we implemented. However, the application doesn’t know about this extension type, and so complains about it.

This problem will be fixed in the Oct2020-SP4, which we are preparing.  The solution is for the ODBC driver to translate the `HUGEINT` column to `BIGINT`, a type that is part of the ODBC standard. When doing this, there should not be any negative consequences: if the values fit in a `BIGINT`, there will be no error; if the values don't fit in a `BIGINT`, there will be an overflow error.  In the second case, the error is expected, since the application doesn't recognise the `HUGEINT` type, an overflow error is bound to happen somewhere.

**Comment by suryanmohanty** [comment] 2021-04-04 16:25
Thanks Ying, may i know when SP4 will be avaliable.

**Comment by PedroTadim** [comment] 2021-04-08 06:30
It should be available around next week.

**Comment by PedroTadim** [comment] 2021-04-13 11:50
Oct2020-SP4 has been released.

**Closed as completed by PedroTadim** 2021-04-13 11:50 UTC
Labels: bug
