### ISSUE TITLE
If truncate is in transaction then after restart of MonetDB the table is empty

### ISSUE THREAD

**Issue by v-from-meiro** [MonetDB/MonetDB#7173] opened 2021-09-03 07:32 UTC
**Describe the bug**
If truncate is in transaction then after restart of MonetDB the table is empty.

**To Reproduce**
```
create table test (col int);
insert into test values (1), (2), (3);

begin transaction;
create table test_new (col int);
commit;

begin transaction;
truncate table test_new; -- if I do not do this, then everything works as expected
insert into test_new select * from test;
drop table test;
alter table test_new rename to test;
commit;

select * from test;

-- restart monetdb

select * from test;
```

**Expected behavior**
The table should keep the data.

**Software versions**
 - MonetDB version number Jul2021

**Comment by yzchang** [comment] 2021-09-03 11:28
I can reproduce this.  Also, replacing the `truncate` query with `delete from test_new` produces the same problem, which is probably because both queries share the same underlying implementation.

**Comment by njnes** [comment] 2021-09-06 14:58
seems the bitvector for the used rows wasn't stored. Fixed in top of tree

**Closed as completed** 2021-09-06 14:58 UTC
Labels: bug
