### ISSUE TITLE
count(distinct ) not working - distinct directive ignored ?

### ISSUE THREAD

**Issue by manuelpagliaivisokio** [MonetDB/MonetDB#7145] opened 2021-06-24 10:47 UTC
[BondPricesWithNulls.txt](https://github.com/MonetDB/MonetDB/files/6708572/BondPricesWithNulls.txt)

I think I discovered a bug in  MonetDB v11.39.17 (Oct2020-SP5).
I attached the sql to re-create the table.

The query:
```

  select
         count(distinct "t27"."Category") as "c29_category__unique_count__2"
         from
         (
            select *
            from "BondPricesWithNulls" as "t6"
            where
            (
               "Category" = 'Supranational'
            )
         )
         as "t27"
         group by "t27"."Category"

```
returns :
```
c29_category__unique_count__2
-----------------------------
                           94
```

Although the correct value is clearly 1.  Similar issues happen with non text columns.

The database can be tricked by changing the select list into

` count(distinct concat('',"t27"."Category")) as "c29_category__unique_count__2"`

which is should be equivalent, yet with that change the correct result is retuned.

If if you can think of a better work-around for this issue, it would be greatly appreciated.

**Comment by PedroTadim** [comment] 2021-06-24 11:38
This seems to be a duplicate of https://github.com/MonetDB/MonetDB/issues/7141 It should be fixed in the next release.

**Closed as completed** 2021-07-08 13:23 UTC
Labels: other
