### ISSUE TITLE
Logical Expression Evaluation Bug in WHERE Clause with Constant Conditions

### ISSUE THREAD

**Issue by akuluasan** [MonetDB/MonetDB#7591] opened 2024-10-29 13:57 UTC
### Describe the bug

```sql

SELECT * FROM t0 WHERE t0.c0 = ''  ;
  ┌─c0─┐
1. │    │
2. │    │
   └────┘

2 rows in set. Elapsed: 0.001 sec. 

SELECT * FROM t0 WHERE (t0.c0 = '') AND (0.23314537804241876) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND (NOT (0.23314537804241876)) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND ((0.23314537804241876) IS NULL);

Ok.

0 rows in set. Elapsed: 0.002 sec. 
```

This test case reveals a bug due to an inconsistency in handling logical expressions with constants in the WHERE clause. 

The logical condition (0.23314537804241876 OR NOT 0.23314537804241876 OR 0.23314537804241876 IS NULL) evaluates to TRUE, as it should cover all possible outcomes (true, false, null). 

Therefore, all rows where t0.c0 = '' should be returned, matching the first query's results. However, the second query with the UNION ALL logic returns zero rows, indicating a bug where constant-based logical expressions are not correctly evaluated across queries.

### Reproduction steps

```sql
drop table if exists t0;
CREATE TABLE t0 (c0 String) ENGINE = MergeTree() ORDER BY c0;
INSERT INTO t0 (c0) VALUES (''), ('');

SELECT * FROM t0 WHERE t0.c0 = ''  ;

SELECT * FROM t0 WHERE (t0.c0 = '') AND (0.23314537804241876) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND (NOT (0.23314537804241876)) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND ((0.23314537804241876) IS NULL);
```

### Expected behavior

return the same result

### MonetDB release

MonetDB 5 server 11.51.3 (Aug2024) (64-bit, 128-bit integers)

### Executables source

Release packages

### Operating System

ubuntu 20.04

**Comment by mvdvm** [comment] 2024-10-31 14:42
Your query
```
SELECT * FROM t0 WHERE (t0.c0 = '') AND (0.23314537804241876) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND (NOT (0.23314537804241876)) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND ((0.23314537804241876) IS NULL);
```
returns error message:  `types decimal(18,17) and boolean(1,0) are not equal`

Also the query
```
SELECT (0.23314537804241876 OR NOT 0.23314537804241876 OR 0.23314537804241876 IS NULL);
```
returns an error:  `SELECT: no such unary operator 'sys'.'not'(decimal)`

You cannot use decimals where booleans or boolean logic is expected.
You will need to adapt your query. For instance:
```
SELECT * FROM t0 WHERE (t0.c0 = '') AND (0.23314537804241876 <> 0) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND (NOT (0.23314537804241876 <> 0)) UNION ALL 
SELECT * FROM t0 WHERE (t0.c0 = '') AND ((0.23314537804241876) IS NULL);
```
Maybe that is what you intended to do.

And
```
SELECT (0.23314537804241876 <> 0 OR NOT 0.23314537804241876 <> 0 OR 0.23314537804241876 IS NULL);
```
will return `true` instead of the syntax error.

As this is not a bug I closed this issue.
If you do not agree you may reopen it.

**Closed as completed by mvdvm** 2024-10-31 14:42 UTC
Labels: other
