### ISSUE TITLE
MonetDB server crashes in `sql_init_subtype`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7487] opened 2024-03-17 11:51 UTC
**Describe the bug**
MonetDB server crashes in `sql_init_subtype`.

**To Reproduce**
```sql
SELECT levenshtein ( 'int' , '2014-10-25 UTC' );
```

**Backtrace of the Crash**
```c
#0 0x7ff2f16795ec (sql_init_subtype+0x3c)
#1 0x7ff2f16b855b (res_col_create+0xdb)
#2 0x7ff2f1582d96 (mvc_result_value+0x66)
#3 0x7ff2f14f2940 (mvc_scalar_value_wrap+0x210)
#4 0x7ff2f1a67dad (runMALsequence+0xe8d)
#5 0x7ff2f1a66ace (runMAL+0xee)
#6 0x7ff2f150d9d2 (SQLrun+0x142)
#7 0x7ff2f150f499 (SQLengineIntern+0xc9)
#8 0x7ff2f150c0d2 (SQLengine_+0x1122)
#9 0x7ff2f15091fe (SQLengine+0x3e)
#10 0x7ff2f1a8db2f (runScenario+0x6f)
#11 0x7ff2f1a8ecfe (MSscheduleClient+0xb6e)
#12 0x7ff2f1bd26c2 (doChallenge+0x132)
#13 0x7ff2f29efb38 (thread_starter+0x318)
#14 0x7ff2f1400609 (start_thread+0xd9)
#15 0x7ff2f1323353 (clone+0x43)
```

**Software versions**
 - MonetDB version number: v11.49.1 (Dec2023)
 - OS and version: Ubuntu 20.04
 - From docker image monetdb/monetdb:Dec2023 (or monetdb/dev-builds:default)

An example of steps to reproduce in docker container (**write the poc into /tmp/test.sql first**):
```bash
docker container rm monetdb_test -f
docker run -e MDB_DB_ADMIN_PASS=monetdb --name monetdb_test -itd monetdb/monetdb:Dec2023
docker exec monetdb_test bash -c 'echo -n -e "user=monetdb\npassword=monetdb\n" > /root/.monetdb'

sleep 10
cat /tmp/test.sql | timeout 5s docker exec -i monetdb_test mclient monetdb     # run test case

if docker exec monetdb_test bash -c "grep '[m]server5' /proc/*/cmdline -lR"; then
    echo "[INFO] Server normal."
else
    echo "[CRASH] Mserver5 process does NOT exist."
fi
```

It can also be reproduced on the docker image `monetdb/dev-builds:default`.

**Issue labeling**
bug

**Comment by mvdvm** [comment] 2024-03-20 20:27
The first argument value 'int' seems to cause the problem.

**Comment by lrpereira** [comment] 2024-05-03 11:38
Duplicate of #7509.

**Closed as completed by lrpereira** 2024-05-03 11:38 UTC
Labels: other
