### ISSUE TITLE
MonetDB server 11.46.0 crashes at `gc_col`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7382] opened 2023-06-16 17:28 UTC
**Describe the bug**
MonetDB server 11.46.0 crashes at `gc_col` after executing SQL statements through ODBC.

**To Reproduce**
1. Configure the unixODBC with MonetDB ODBC drivers
2. Use the command line like `isql monetdb -v -e` to connect (**to trigger the crash, the '-e' option is necessary.** But I don't know why)
3. Execute the following SQL statements:
```sql
START TRANSACTION;
CREATE TEMPORARY TABLE t1 (keyc INT, c1 VARCHAR(100), c2 VARCHAR(100), PRIMARY KEY(keyc));
CREATE TABLE c1(c2 DECIMAL(9,4) NOT NULL);
SAVEPOINT a_a;
TRUNCATE TABLE t1;
DELETE FROM w;
COMMIT;
SELECT 1;
```

**Expected behavior**
Executing statements successfully or throwing errors, instead of breaking down the whole MonetDB server.

**Backtrace**
```
#0 0x7ff2e7285dd6 (gc_col+0x26)
#1 0x7ff2e7282cd5 (tc_gc_col+0x15)
#2 0x7ff2e7251307 (store_pending_changes+0x307)
#3 0x7ff2e7255a87 (sql_trans_commit+0x567)
#4 0x7ff2e7260353 (sql_trans_end+0x83)
#5 0x7ff2e72a310c (mvc_commit+0x4fc)
#6 0x7ff2e71a4564 (SQLengine_+0x284)
#7 0x7ff2e71a3343 (SQLengine+0x23)
#8 0x7ff2e75326cf (runScenario+0x4f)
#9 0x7ff2e753316c (MSscheduleClient+0x68c)
#10 0x7ff2e75dac2b (doChallenge+0xfb)
#11 0x7ff2e7c59ba0 (THRstarter+0x100)
#12 0x7ff2e7cc9cc4 (thread_starter+0x34)
#13 0x7ff2e703e609 (start_thread+0xd9)
#14 0x7ff2e6f63133 (clone+0x43)
```

**Software versions**
 - MonetDB server version: 11.46.0 (hg id: 63a42c2) (pulled from the master branch)
 - MonetDB client version: mclient, version 11.48.0 (hg id: 63a42c2)
 - OS and version: ubuntu 20.04
 - Self-installed and compiled. The command line of compilation: `CC=clang-12 CXX=clang++-12 cmake /root/monetdb_master -DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Issue labeling**
bug

**Additional context**
The MonetDB here runs in-memory database. The command line of starting MonetDB server is `mserver5 --in-memory`.

If the crash cannot be reproduced easily, please tell me. I will try to provide the whole steps to trigger the crash as possible.

**Comment by mvdvm** [comment] 2023-06-19 15:44
Could **not** reproduce the crash with MonetDB 5 server v11.45.17 (Sep2022-SP3).
The statement `TRUNCATE TABLE t1;` fails with error: `TRUNCATE: no such table 't1'`.
The statement `DELETE FROM w;` fails with error: `DELETE FROM: no such table 'w'`.
The next statement `COMMIT;` therefore fails with error: `COMMIT: transaction is aborted, will ROLLBACK instead`
No crash of server.
I noticed that without the `SAVEPOINT a_a;` statement the `TRUNCATE TABLE t1;` statement succeeds, so setting the savepoint apparently 'looses' the temp table information, which is incorrect.

**Comment by mvdvm** [comment] 2023-06-19 16:05
Crash is **not** reproducable with MonetDB 5 server v11.45.17 (Sep2022-SP3).
Statement `TRUNCATE TABLE t1;` fails with error: `TRUNCATE: no such table 't1'`.
Without the statement `SAVEPOINT a_a;` the `TRUNCATE TABLE t1;` succeeds however, so there may be a bug here.
Statement `DELETE FROM w;` fails with error: `DELETE FROM: no such table 'w'`. Do you have a table definition for table w or is this intended to fail?
Statement `COMMIT;` fails with error: `COMMIT: transaction is aborted, will ROLLBACK instead`.
No crash of server.

**Comment by njnes** [comment] 2023-06-19 16:49
fixed in https://www.monetdb.org/hg/MonetDB/rev/8f0cdfbe7601

**Closed as completed by njnes** 2023-06-19 16:49 UTC
Labels: bug
