### ISSUE TITLE
Creating temporary table fails after reconnect

### ISSUE THREAD

**Issue by oflaschel** [MonetDB/MonetDB#7330] opened 2022-10-18 09:50 UTC
**Describe the bug**
Creating of a temporary table fails after reconnect.

**To Reproduce**
```
~$ sudo -u monetdb monetdb create test_bug
created database in maintenance mode: test_bug
~$ sudo -u monetdb monetdb release test_bug
taken database out of maintenance mode: test_bug
~$ mclient -d test_bug -u monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Sep2022)
Database: MonetDB v11.45.7 (Sep2022), 'mapi:monetdb://luna:50000/test_bug'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TEMP TABLE tmp.test (id bigint NOT NULL PRIMARY KEY);
operation successful
sql>exit
~$ mclient -d test_bug -u monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Sep2022)
Database: MonetDB v11.45.7 (Sep2022), 'mapi:monetdb://luna:50000/test_bug'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TEMP TABLE tmp.test (id bigint NOT NULL PRIMARY KEY);
CONSTRAINT PRIMARY KEY: key test_id_pkey already exists
```
Stopping the database seem to heal the problem:
```
~$ sudo -u monetdb monetdb stop test_bug
stopping database 'test_bug'... done
~$ mclient -d test_bug -u monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Sep2022)
Database: MonetDB v11.45.7 (Sep2022), 'mapi:monetdb://luna:50000/test_bug'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TEMP TABLE tmp.test (id bigint NOT NULL PRIMARY KEY);
operation successful
sql>exit
```

**Expected behavior**
The second attempt of creating the temporary table should not fail.
Here the same test with an older version of MonetDB:
```
~$ sudo -u monetdb monetdb create test_bug
created database in maintenance mode: test_bug
~$ sudo -u monetdb monetdb release test_bug
taken database out of maintenance mode: test_bug
~$ mclient -d test_bug -u monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Nov2019-SP1)
Database: MonetDB v11.35.9 (Nov2019-SP1), 'mapi:monetdb://bigone1:50000/test_bug'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TEMP TABLE tmp.test (id bigint NOT NULL PRIMARY KEY);
operation successful
sql>exit
~$ mclient -d test_bug -u monetdb
password:
Welcome to mclient, the MonetDB/SQL interactive terminal (Nov2019-SP1)
Database: MonetDB v11.35.9 (Nov2019-SP1), 'mapi:monetdb://bigone1:50000/test_bug'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>CREATE TEMP TABLE tmp.test (id bigint NOT NULL PRIMARY KEY);
operation successful
sql>exit
```

**Software versions**
 - MonetDB v11.45.7 (Sep2022)
 - Ubuntu 20.04
 - Installed from release package

**Additional context**
Using **pymonetdb** shows same behavior.

**Comment by aris-koning** [comment] 2022-10-19 11:58
Thanks for reporting. I was able to reproduce this on Sep2022 and Jan2022 SP5. but not on older SN and major releases. We will have a look at it in due time.

**Comment by njnes** [comment] 2022-10-21 17:25
fix was pushed on the Sep2022 branch

**Comment by oflaschel** [comment] 2022-10-25 07:52
Thank you very much for the quick fix!
I tested the changes and now see the **expected behavior** described above.
I had to hack a little bit to build the deb packages.
I used `cpack -G DEB .` to build them but `${shlibs:Depends}`, `${misc:Depends}` and `${source:Version}` variables were not properly evaluated.
I helped myself by just removing `${shlibs:Depends}` and `${misc:Depends}` and replacing `${source:Version}` by 11.45.8 in the CPackConfig.cmake file.
Is there some documentation regarding the building of the deb packages?

**Comment by sjoerdmullender** [comment] 2022-11-09 08:43
Closing this since the main issue was fixed.

As to building deb packages, we use a combination of `sudo pbuilder --create` and `pdebuild --use-pdebuild-internal` which use the `debian` subdirectory.  We do not use `cpack`.

**Closed as completed by sjoerdmullender** 2022-11-09 08:43 UTC
Labels: bug
