### ISSUE TITLE
MALException when running select query after monetdbe_append in MonetDBe

### ISSUE THREAD

**Issue by arifsaeed** [MonetDB/MonetDB#7091] opened 2021-03-29 13:24 UTC
**Describe the bug**
I am trying to integrate Monetdbe into a C++ application.

When a SELECT statement is run after running the monetdbe_append function, the Select query returns the following error:

`MALException:algebra.projection:GDK reported error.`

If I do not use monetdbe_append, but insert into the table using the following code, the SELECT statement works fine.

```
if (monetdbe_query(db, "INSERT INTO integers VALUES (3, 4), (5, 6), (7, NULL);", NULL, &rows_affected) != NULL) {
		fprintf(stderr, "Failed to query database\n");
	}

```
**To Reproduce**
created a C++ application using CMAKE.  In the CMakeLists.txt file set the following
in target_link_libraries include MonetDB-master/build/tools/monetdbe/libmonetdbe.so
In target_include_directories point to the following files:
monetdbe.h 
monetdb_config.h

in the main.cpp file copy the following code(this is adapted form the copy_into.c examples file):
```
int main(){

	monetdbe_database db = NULL;
	monetdbe_result *result;
	monetdbe_column *cols[2];
	monetdbe_cnt rows_affected = 0;

    char* err;
    char createSQL[100]="CREATE TABLE integers(i INTEGER, j INTEGER);";
    char insertIntoSQL[100]="INSERT INTO integers VALUES (3, 4), (5, 6), (7, 8);";
    char selectSQL[100]="SELECT * FROM integers";

	if (monetdbe_open(&db, NULL /* inmemory database */, NULL /* no options */)) {
		fprintf(stderr, "Failed to open database\n");
		return -1;
	}
	if (monetdbe_query(db, createSQL, NULL, NULL) != NULL) {
		fprintf(stderr, "Failed to query database\n");
	}

  int32_t intsI[3] = { 3, 5, 7};
	monetdbe_column col0 = { .type = monetdbe_int32_t, .data = &intsI, .count = 2 };

  int32_t intsJ[3] = { 4, 6,8};
	monetdbe_column col1 = { .type = monetdbe_int32_t, .data = &intsJ, .count = 2 };

  monetdbe_column* dcol[2] = { &col0, &col1};

  monetdbe_append(db, "sys", "integers",  (monetdbe_column**) &dcol, 2);
	//if (monetdbe_query(db, insertIntoSQL, NULL, &rows_affected) != NULL) {
	//	fprintf(stderr, "Failed to query database\n");
	//}
    err = monetdbe_query(db, selectSQL, &result, NULL);
	if (err != NULL) {
		printf("%s\r\n", err);
	}
	// print the names of the result
	for (size_t i = 0; i < result->ncols; i++) {
		monetdbe_result_fetch(result, &cols[i], i);
		printf("%s ", cols[i]->name);
	}

	printf("\r\n");

	// print the data of the result
	for (size_t row_idx = 0; row_idx < result->nrows; row_idx++) {
		for (size_t col_idx = 0; col_idx < result->ncols; col_idx++) {
			assert(cols[col_idx]->type == monetdbe_int32_t);
			monetdbe_column_int32_t *col = (monetdbe_column_int32_t *)cols[col_idx];
			int val = col->data[row_idx];
			if (val == col->null_value)
				printf("NULL ");
			else
				printf("%d ", val);
		}
		printf("\n");
	}

	return 0;
}
```

**Expected behavior**
I would expect the line err = monetdbe_query(db, selectSQL, &result, NULL); to run successfully

**Screenshots**

**Software versions**
 - I downloaded the Monetdb source Code after Oct2020
 - Ubuntu 20.04
 - I followed the following instructions to install monetDB locally
         git clone https://github.com/MonetDB/MonetDB MonetDB 
         cd MonetDB
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

**Issue labeling **
Bug

**Additional context**

**Comment by PedroTadim** [comment] 2021-03-30 07:27
I can't reproduce your issue. At which commit did you compile the source from? From your example, I see the integer arrays have 3 elements each, but only 2 are inserted. Also why aren't you checking the result of monetdbe_append, cleaning the result set and shutting down the database?

**Comment by arifsaeed** [comment] 2021-03-30 10:58
Unfortunately, I don't know what commit I used.  I simply downloaded the zip file from the following location: https://github.com/MonetDB/MonetDB  around the 25th of Feb 2021.  

If you have a specific version you would like me to try, please let me know.

I fixed the issues you highlighted, sorry that was me being tardy.  I then reconfigured the code to close and re-open the database after the append.  This allowed me to run the SELECT statement, and I got the following output.

It looks like the append did not work as expected, i.e. I was expecting only three rows but looks like the command created 6 rows, with uninitialized values.

I             J
3            NULL
5            NULL
7            NULL
0            4
0            6
0            8

Do you have any tips on what I can do next to try and debug this issue?

   ************************************************************************************************
I have included my updated code below:
```
#include "monetdbe.h"
#include <string>
#include <iostream>

#define error(msg) {fprintf(stderr, "Failure: %s\n", msg); return -1;}

int main(){

	monetdbe_database db = NULL;
	monetdbe_result *result;
	monetdbe_column *cols[2];
	monetdbe_cnt rows_affected = 0;

    char* err;
    char createSQL[100]="CREATE TABLE integers(i INTEGER, j INTEGER);";
    char insertIntoSQL[100]="INSERT INTO integers VALUES (3, 4), (5, 6), (7, 8);";
    char selectSQL[100]="SELECT * FROM integers";
    char createSchema[100]="CREATE SCHEMA bp";
    char setSchema[100]="SET SCHEMA bp";
    char selectCurrSchema[30]=" SELECT CURRENT_SCHEMA";
	char url[100]="/home/arif/Documents/models/dbs/abstraca";
	
	//open db
	if (monetdbe_open(&db, url /* inmemory database */, NULL /* no options */)) {
		fprintf(stderr, "Failed to open database\n");
		return -1;
	}

    if (monetdbe_query(db, createSchema, NULL, NULL) != NULL) {
		fprintf(stderr, "Failed to createSchema\n");
	}

    err=monetdbe_query(db, setSchema, NULL, NULL);
    if (err != NULL) {
		printf("%s\r\n", err);
	}

	if (monetdbe_query(db, createSQL, NULL, NULL) != NULL) {
		fprintf(stderr, "Failed to query database\n");
	}



  int32_t intsI[3] = { 3, 5, 7};
	monetdbe_column col0 = { .type = monetdbe_int32_t, .data = &intsI, .count = 3 };

  int32_t intsJ[3] = { 4, 6, 8};
	monetdbe_column col1 = { .type = monetdbe_int32_t, .data = &intsJ, .count = 3 };

  monetdbe_column* dcol[2] = { &col0, &col1};

  char bpschema[3]="bp";
  char table[9]="integers";
  err =monetdbe_append(db, bpschema, table,  (monetdbe_column**) &dcol, 2);
  if (err != NULL) {
		printf("%s\r\n", err);
	}


	if (monetdbe_close(db))
		error("Failed to close database")
	
	
	if (monetdbe_open(&db, url /* inmemory database */, NULL /* no options */)) {
		fprintf(stderr, "Failed to open database\n");
		return -1;
	}

    err=monetdbe_query(db, setSchema, NULL, NULL);
    if (err != NULL) {
		printf("%s\r\n", err);
	}

    err = monetdbe_query(db, selectSQL, &result, NULL);
	if (err != NULL) {
		printf("%s\r\n", err);
	}
	// print the names of the result
	for (size_t i = 0; i < result->ncols; i++) {
		monetdbe_result_fetch(result, &cols[i], i);
		printf("%s ", cols[i]->name);
	}

	printf("\r\n");

	// print the data of the result
	for (size_t row_idx = 0; row_idx < result->nrows; row_idx++) {
		for (size_t col_idx = 0; col_idx < result->ncols; col_idx++) {
			assert(cols[col_idx]->type == monetdbe_int32_t);
			monetdbe_column_int32_t *col = (monetdbe_column_int32_t *)cols[col_idx];
			int val = col->data[row_idx];
			if (val == col->null_value)
				printf("NULL ");
			else
				printf("%d ", val);
		}
		printf("\n");
	}

	if ((err = monetdbe_cleanup_result(db, result)) != NULL)
		error(err)

	if (monetdbe_close(db))
		error("Failed to close database")
	return 0;


    std::cout<<"finished"<<std::endl;
	return 0;
}
```

**Comment by yzchang** [comment] 2021-03-30 11:15
the "master" branch is under heavy development.  A version from Feb. is ancient.  Please update your MonetDB installation and retry.

**Comment by PedroTadim** [comment] 2021-03-30 11:17
Now I'm confused, which branch did you try from? default/master or Oct2020? default/master is very unstable at the moment, so please don't use it for production workloads yet.

**Comment by arifsaeed** [comment] 2021-03-30 12:39
Sorry for the confusion I downloaded from default/master.  
I should know this but I don't know where to get a stable/recent release of your code.  
Can you please provide a link.  

I assume it's not the page below, as that installs Monetdb on my system and I cant see how to integrate Monetdbe from this into my C++ application.
https://www.monetdb.org/downloads/deb/

**Comment by PedroTadim** [comment] 2021-03-30 12:45
It's fine, you can check the tags here: https://github.com/MonetDB/MonetDB/tags for the release commits.

**Comment by arifsaeed** [comment] 2021-03-30 13:32
I downloaded the Oct2020_SP3_release  and it worked.  
Thank you for all your help.

**Comment by PedroTadim** [comment] 2021-03-30 14:22
I am going to close this issue.

**Closed as completed by PedroTadim** 2021-03-30 14:22 UTC
Labels: other
