### ISSUE TITLE
Query execution does not stop despite disconnection

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7122] opened 2021-05-08 20:01 UTC
**Describe the bug**
In some cases of "expensive" SELECT-only queries, possibly with queries being made over more than one connection, mserver5 does not stop executing said queries for at least 1 minute (possibly a lot more - I killed the processes) despite the connection which made them having been terminated (Ctrl+C). The number of workers is listed as 0, but the `htop` utility shows a whole lot of CPU use (when there are no other outstanding queries).

I should mention that while this was happening, there was a whole lot of thrashing between memory and disk; might have had something to do with it.

**Expected behavior**
Once an mclient connection is terminated, then within a very brief period (less than a second) execution of any SELECT-only queries issued on that connection should cease. The same should probably true for any statement I suppose.

**Screenshots**

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from sources

**Comment by yzchang** [comment] 2021-05-10 08:11
See #7112

**Comment by PedroTadim** [comment] 2021-05-27 12:30
I am going to close this issue as a duplicate of #7112

**Closed as completed by PedroTadim** 2021-05-27 12:30 UTC
Labels: other
