### ISSUE TITLE
DELETE FROM or TRUNCATE on freshly created table leads to loosing all further inserts in same transaction

### ISSUE THREAD

**Issue by jniewerth** [MonetDB/MonetDB#7024] opened 2020-12-11 09:36 UTC
When doing a DELETE FROM or TRUNCATE on a freshly created table all further INSERTs in the same transaction are lost.

Example:

```
mclient db
Welcome to mclient, the MonetDB/SQL interactive terminal (Oct2020-SP1)
Database: MonetDB v11.39.7 (Oct2020-SP1), 'mapi:monetdb://28be88be3df8:50000/oohreporting'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>START TRANSACTION;
auto commit mode: off
sql>CREATE TABLE b (c integer);
operation successful
sql>DELETE FROM b;
0 affected rows
sql>INSERT INTO b VALUES (1);
1 affected row
sql>COMMIT;
auto commit mode: on
sql>SELECT * FROM b;
+---+
| c |
+===+
+---+
0 tuples
``

**Comment by PedroTadim** [comment] 2020-12-11 11:26
I can't reproduce this issue on my setup. Maybe it got fixed after the release.

**Comment by njnes** [comment] 2020-12-11 12:21
I found something similar (ie empty table). When I run the script (with 2 sessions after each other), the second finds b empty.
This is now fixed in https://dev.monetdb.org/hg/MonetDB/rev/66645aea30c4.

**Comment by njnes** [comment] 2020-12-15 16:35
did the fix help?

**Closed as completed by njnes** 2020-12-15 16:35 UTC
Labels: bug
