### ISSUE TITLE
Database crashes when use similarity function on a table with more than 200k records 

### ISSUE THREAD

**Issue by thomasguo** [MonetDB/MonetDB#7016] opened 2020-12-05 06:14 UTC
**Describe the bug**
In we use the built-in similarity function in query sql and the nubmer of rows in table exceed 200K, the database crashes.

**To Reproduce**
-- Create a table named t_199999 and populated with 199999 rows;
CREATE TABLE t_199999 (s1 string, s2 string);
-- Create a table named t_200000 and populated with 200000 rows;
CREATE TABLE t_200000 (s1 string, s2 string);

execute the sql query:
-- this works well
select count(1) from t_199999 where similarity(s1, s2)> 0.5;  
-- this crashes the database
select count(1) from t_200000 where similarity(s1, s2)> 0.5;  

**Expected behavior**
the database should work well if we use similarity function even if the table row numbers exceed 200000.

**Software versions**
 - MonetDB version number [x86_64-20201013]
 - OS and version: [both Window 7 and Centos 7]
 - Installed from release package

**Comment by PedroTadim** [comment] 2020-12-05 07:41
Hello thomas, can you send a more detailed reproducible script? I can't reproduce the issue on my setup.

**Comment by PedroTadim** [comment] 2020-12-05 08:30
After some more research I found out there are some global variables on similarity function that may cause issues on parallel execution. I didn't write this function, but it seems to be bad. I will fix it later today.

**Comment by thomasguo** [comment] 2020-12-06 08:16
Hello Pedro, thanks for your prompt reply.  The table schema is very simple because it only contains 2 string columns.  FYI here are 2 sample data files exported from my testing db.  Hope this would be helpful.
[t_199999.csv.gz](https://github.com/MonetDB/MonetDB/files/5648463/t_199999.csv.gz)
[t_200000.csv.gz](https://github.com/MonetDB/MonetDB/files/5648464/t_200000.csv.gz)

**Comment by PedroTadim** [comment] 2020-12-07 09:51
I just fixed it on Oct2020 development branch. I also made the function faster by reducing some function calls and allocations. If you can compile the sources, please test there, so we can close this issue.

**Comment by thomasguo** [comment] 2020-12-07 18:52
I have compiled the sources from master branch (on CentOS 7) and the similarity function works correctly.  Not tested it on microsoft Windows yet because I have no idea about how to compile monetdb sources on this platform.  Is there any instruction information about doing that, please?

BTW,  it seems that the new development monetdb server (v11.40.0) could not been connected from the release version of mclient(version 11.39.5).   Maybe the wire prototol has been changed?

**Comment by PedroTadim** [comment] 2020-12-08 08:33
Since version 11.39.5 we migrated to Cmake build system. It should be straightforward to build on Windows with it. I recommend installing vcpkg: https://github.com/Microsoft/vcpkg on Windows for dependencies management. Download and install dependencies on vcpkg and use it as a Cmake toolchain file: cmake -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg.cmake> ...  The packages required are pcre, openssl and libxml2. Outside vcpkg, python3 is required as well as bison. One of my colleagues made a tutorial here: https://monetdb-solutions-monetdb.readthedocs-hosted.com/en/branches-oct2020/source/build.html

I did run monetdb server 11.40.0 on my machine locally and connected with mclient 11.39.8 successfully. There was a user on the mailing list having issues connecting to a server on Windows and it had to do with the listening address of the server which was just accepting connections locally.

**Closed as completed** 2020-12-11 08:07 UTC
Labels: bug
