### ISSUE TITLE
Query produces this error and is not shown on the screen: !ERROR: Could not find (null).c0

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7156] opened 2021-07-13 18:03 UTC
**Describe the bug**
The query does not execute because an internal error (crash) occurs and nothing appears on the screen.
But inside MonetDB server an error occurs.

**To Reproduce**
Run the SELECT command below:
select
	A c0,
	count(distinct A) c1
from
	(
		select 'a' A, '1' B
		union all
		select 'a', '2'
		union all
		select 'a', '3'
		union all
		select 'b', '4'
		union all
		select 'b', '5'
		union all
		select 'c', '6'
	) T
group by
	grouping sets ((c0), ())

**Expected behavior**
The error message appears on the screen or the command will run successfully if there is no syntax problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/86444458/125502256-f388be0c-714b-4c4c-973e-d249d0aba410.png)
![image](https://user-images.githubusercontent.com/86444458/125502583-0a75d17d-75ce-44e5-b988-ec28f6569bcc.png)

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
 - OS and version: [Windows 10 Pro 64 bits - 20H2]
 - Installed from release package

**Comment by PedroTadim** [comment] 2021-07-14 07:39
On the tip of the Oct2020 development branch I get the right results. This must be a duplicate of another bug.

**Comment by PedroTadim** [comment] 2021-07-14 11:52
Is is a duplicate of bug #7146 It will be fixed in the next release.

**Closed as completed** 2021-07-15 14:02 UTC
Labels: other
