### ISSUE TITLE
Procedure vanishing

### ISSUE THREAD

**Issue by zltpfp89** [MonetDB/MonetDB#7317] opened 2022-07-25 01:19 UTC
This is my first time using MonetDB and something weird happened.
The procedures often vanish with no reason.
Below is the version I'm using.

MonetDB version  : 11.43.15 (Jan2022-SP3)
OS : CentOS8(kernel version : 4.18.0-394.el8.x86_64)

Attach the procedure script for further information.
I erased some comments written in Korean...

      CREATE	OR	REPLACE	PROCEDURE	DSDMT.SP_PRSN_CUST_MAPPING_SCRT (IN_BQY_CD	STRING)
      BEGIN
      
	      INSERT	INTO	DSDMT.PRSN_CUST_MAPPING_SCRT
	      (
		      CUST_ID		
	      --   , CUST_SRNO	   
		       , BQY_CD			
	      --   , LOAD_DTM			
	      , LOAD_PGM_ID		
	      )
	      SELECT	T1.CUST_ID					AS	CUST_ID	
		       ,	T1.BQY_CD						AS	BQY_CD			
		       ,	'PRSN_CUST_MAPPING_SCRT.sql' 	AS	LOAD_PGM_ID		
	        FROM	DSDMT.PRSN_MKT_ANA_SCRT_SRC						T1
			      LEFT OUTER JOIN	DSDMT.PRSN_CUST_MAPPING_SCRT	T2
						      ON T1.CUST_ID	=	T2.CUST_ID
	       WHERE	1 = 1
	         AND	T1.BQY_CD		=	IN_BQY_CD
	         AND	T2.CUST_SRNO	IS	NULL
	      ;
      
      END;

This is an example of procedures I've made. 
There were five procedures and the next day I check, there is only one left. Sometimes two.
What can cause this vanishing?

**Comment by lrpereira** [comment] 2022-07-25 13:12
Hi @zltpfp89
Thanks for creating the GH issue as suggested.
This is unusual behaviour and we are interested in figuring out why this is happening.
Are you able to provide a detailed reproducible script up until the point where the procedures seem to "vanish"? (eg, step by step of server and client usage, how are you realizing that the procedure does not exist anymore, etc)
We are not aware of any issue related to the one you are reporting and I cannot reproduce it with the info that you provided.

**Comment by njnes** [comment] 2022-08-02 20:32
how did you verify that the procedure isn't there anymore?

**Comment by zltpfp89** [comment] 2022-08-08 08:30
I’m using dbeaver as a db tool. Right after making procedures, I can see the list of procedures under the schema I’m using. I don’t know when exactly procedures vanish.
Not all of them vanishes, one or two of them are left.

**Comment by aris-koning** [comment] 2022-08-09 07:22
Do you restart your system? What is the time between the definition of your procedures and there apparent disappearing? Can you perhaps create a reproduction scenario with some dummy procedures with all the precise details on what when happens? Perhaps we can then reproduce it.

**Comment by njnes** [comment] 2022-09-24 10:59
please try to verify if this is fixed with the sp4.

**Closed as completed** 2023-09-13 14:44 UTC
