### ISSUE TITLE
JDBC ERROR: Could not allocate space SQLState:  M0M10

### ISSUE THREAD

**Issue by fhoess** [MonetDB/MonetDB#7346] opened 2022-12-16 15:22 UTC
**Describe the bug**
We got the following error, when executing SELECT col_1 FROM table;   Where col_1 is BLOB
other tabels with BLOB columns working fine.
Select other columns of that table is working fine, too.

Error: protocol violation: unexpected line in data block: !45000!Result set construction failed: Could not allocate space
SQLState:  M0M10
ErrorCode: 0

**To Reproduce**
tried with JDBC driver 2.29 and 3.2
I installed 11.45.11 just yesterday. updated from (11.45.7)

**Expected behavior**
no SQL exception

**Screenshots**

**Software versions**
 - MonetDB version number 11.45.11
 - OS and version: Ubuntu 20]
 - Installed from release package

**Issue labeling **

**Additional context**

**Comment by fhoess** [comment] 2022-12-16 15:42
Ok. Seems to be a JDBC problem.
When i use mclient via console, i can use the query without errors

**Comment by fhoess** [comment] 2022-12-16 15:51
FYI: this is working:   SELECT length(col_1) FROM table

With largest length in on row: 1911730793

**Comment by sjoerdmullender** [comment] 2022-12-16 16:30
I wouldn't be surprised if that row length is cause of the problem in the JDBC driver, but I let others who are more familiar with the driver figure that out.

**Comment by fhoess** [comment] 2022-12-19 07:56
Ok. Strange! We check the length of the data in the columns. by SELECT lenght(col1),length(col2) from table:
![image](https://user-images.githubusercontent.com/14872557/208374327-1c44968b-eaf3-4ce1-9ff5-77f0b874a2e5.png)

Column %1 holdes the data of column %2 but "as binary". We expect that the lenght of data is at least highly correlated. Which holds true for all rows, except the first two rows.
We manually delete and replace the rows be re-inserting the data for that two rows and the problems are gone.

The question now is: Why is the data stored incorrectly in the column?

**Comment by sjoerdmullender** [comment] 2022-12-19 09:19
The incorrectly sized data could as well be an application error as an error in MonetDB.
I think we need a reproduction in order to point the finger one way or the other.

**Comment by fhoess** [comment] 2022-12-19 10:31
Ok. We use a prepared statement ps with   ps.setBytes(someJavaByteArray)   with  byte[] someJavaByteArray = ...;

I dont think, that we are able to reproduce this issue.

After re-insert of the rows, everything looks fine:
![image](https://user-images.githubusercontent.com/14872557/208404550-4abc29a0-531c-4b93-842c-af9725348169.png)

Maybe this hint will help you a bit more. For us, the case is closed for the time being. However, we hope that it is not a problem with the database update process. Because the code for the prepared statement was not changed by us for ages.

**Comment by joerivanruth** [comment] 2022-12-20 07:53
One remark: the phrase 'Result set construction failed' is used only in the server, not in the JDBC client. So something was going wrong on the server side, possibly caused by the erroneous length of that value in col_1, and somehow triggered by JDBC and not by mclient.

**Comment by mvdvm** [comment] 2023-02-02 16:35
Closing this issue as we currently have no reproduction program/script for the original reported issue.
Also we do not think it was a problem in the JDBC driver. To verify I have added a test to JDBC_API_Tester.java in our test suite to test methods PreparedStatement.setBytes(param, byte[]) and ResultSet.getBytes(col) of the JDBC driver on a table with blob column and data. It works correctly.

**Closed as completed by mvdvm** 2023-02-02 16:35 UTC
Labels: other
