### ISSUE TITLE
MonetDB Dec2023-SP2 crashes at `sql_init_subtype`

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7509] opened 2024-05-01 20:39 UTC
**Describe the bug**
MonetDB Dec2023-SP2 crashes at `sql_init_subtype`.

**To Reproduce**
```sql
SELECT LEVENSHTEIN('int', 'X2014-10-25 UTC');
```

**Backtrace of the Crash**
```
#0 0x7fc87dce1233 (sql_init_subtype+0x13)
#1 0x7fc87dd05877 (res_col_create+0x87)
#2 0x7fc87dc58851 (mvc_result_value+0x51)
#3 0x7fc87dc04a6c (mvc_scalar_value_wrap+0x12c)
#4 0x7fc87dfd7a5e (runMALsequence+0x79e)
#5 0x7fc87dfd7ddf (runMALsequence+0xb1f)
#6 0x7fc87dfd7073 (runMAL+0xa3)
#7 0x7fc87dc14ab0 (SQLrun+0x100)
#8 0x7fc87dc15cde (SQLengineIntern+0x4e)
#9 0x7fc87dc13af9 (SQLengine_+0xa09)
#10 0x7fc87dc11fc3 (SQLengine+0x23)
#11 0x7fc87dfed5ff (runScenario+0x4f)
#12 0x7fc87dfedfb6 (MSscheduleClient+0x5d6)
#13 0x7fc87e0a0aab (doChallenge+0xfb)
#14 0x7fc87e832f21 (thread_starter+0x191)
#15 0x7fc87db2a609 (start_thread+0xd9)
#16 0x7fc87da4d353 (clone+0x43)
```

**Software versions**
 - MonetDB version number: v11.49.7 (Dec2023-SP2)
 - OS and version: Ubuntu 20.04
 - From docker image monetdb/monetdb:Dec2023-SP2 (or monetdb/dev-builds:default)

**Comment by mvdvm** [comment] 2024-05-02 10:40
This is duplicate of #7487  (only the string 'X2014-10-25 UTC' is different).

**Comment by lrpereira** [comment] 2024-05-03 11:36
Reviewed and tested Sjoerd's patch. The fix is good.

**Closed as completed by lrpereira** 2024-05-03 11:36 UTC
Labels: bug
