### ISSUE TITLE
"count distinct" is not working properly

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7155] opened 2021-07-13 17:44 UTC
**Describe the bug**
"count distinct" is not working properly.

**To Reproduce**
Run this SQL command:
select
	A,
	count(distinct A)
from
	(
		select 'a' A, '1' B
		union all
		select 'a', '2'
		union all
		select 'a', '3'
		union all
		select 'b', '4'
		union all
		select 'b', '5'
		union all
		select 'c', '6'
	) T
group by
	A
The result will be this:
![image](https://user-images.githubusercontent.com/86444458/125499991-cbc5e85c-1cc5-4c9f-99d8-a983adbe7f79.png)

**Expected behavior**
It should always return 1 in the second column.

**Software versions**
 - MonetDB version number [MonetDB 5 server v11.39.17 (Oct2020-SP5)]
 - OS and version: [Windows 10 Pro 64 bits - 20H2]
 - Installed from release package

**Comment by PedroTadim** [comment] 2021-07-14 07:34
This is a duplicate of https://github.com/MonetDB/MonetDB/issues/7141 and https://github.com/MonetDB/MonetDB/issues/7145 It will be fixed on the next release.

**Closed as completed** 2021-07-15 14:02 UTC
Labels: other
